FROM esamarathon/tracker:latest AS builder
WORKDIR /usr/src/app
COPY entrypoint.sh /usr/src/app/
COPY local_statics.py /usr/src/app/local.py
RUN python manage.py collectstatic --noinput

FROM nginx
COPY --from=builder /var/www/static/ /var/www/html/static/
