FROM python:2.7

RUN apt-get update && apt-get install -y \
		gcc \
		gettext \
		default-mysql-client \
		default-libmysqlclient-dev \
		postgresql-client \
		libpq-dev \
		sqlite3 \
		locales-all \
	--no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN pip install gunicorn==19.7.1

RUN mkdir -p /usr/src/app/tracker /usr/src/app/tracker_ui /usr/src/app/db
COPY tracker/requirements.txt /usr/src/app/tracker/
RUN (cd /usr/src/app/tracker && pip install --no-cache-dir -r requirements.txt)

COPY entrypoint.sh /usr/src/app/
COPY *.py *.json /usr/src/app/
COPY tracker/ /usr/src/app/tracker/

WORKDIR /usr/src/app

EXPOSE 8000
CMD ./entrypoint.sh 
