#FROM node:18 AS client
#
#WORKDIR /app
#
#COPY ./tracker/package.json ./tracker/yarn.lock ./
#RUN yarn
#
#COPY \
#  ./tracker/.browserslistrc \
#  ./tracker/karma.conf.js \
#  ./tracker/declarations.d.ts \
#  ./tracker/postcss.config.js \
#  ./tracker/webpack.config.js \
#  ./
#COPY ./tracker/bundles bundles
#COPY ./tracker/tracker tracker
#RUN yarn build

#FROM esamarathon/tracker:latest AS builder
#
#WORKDIR /app/tracker_development
#
#
#
#RUN ls -hal /var/www/static && exit 1
#
#COPY --from=client /app/tracker tracker
#COPY entrypoint.sh /app/tracker_development
#COPY local_statics.py /app/tracker_development/tracker_development/local.py
#
#RUN python manage.py collectstatic --noinput

FROM nginx
#COPY --from=builder /var/www/static/ /var/www/html/static/
RUN mkdir -p /var/www/html/static/res

# TODO: Find a way to include the required fronts
# - cubano-regular
# - MuseoSans_700
# - MuseoSans_300
# - MuseoSans_300

#RUN ls -hal /var/www/html && exit 1
