version: "3.7"
services:
  app:
    image: "esamarathon/tracker:development"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./db/testdb:/usr/src/app/db/testdb"
      - "./blank.json:/usr/src/app/blank.json"
      - "./tracker/:/usr/src/app/tracker/"
      - "./local.py:/usr/src/app/local.py"
      - "static:/var/www/static/:rw"

    environment:
      - TRACKER_ALLOWED_HOSTS="localhost, esatracker.eu.ngrok.io"
      - TRACKER_DOMAIN="localhost"
      - TRACKER_DEBUG=True
#      - TRACKER_DATABASES='{"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": "db/testdb"}}'
      - TRACKER_TIME_ZONE="Europe/Stockholm"
      - TRACKER_SITE_NAME="ESA Dev Tracker"
      - TRACKER_SITE_PREFIX="/"
      - TRACKER_SECRET_KEY="HAhAHAHhahahahhahahhahahhahahahahha"
      - TRACKER_STATIC_URL="/static"
      - TRACKER_STATIC_ROOT="/var/www/static"
      - TRACKER_HAS_GDOC=False
      - TRACKER_HAS_EMAIL=False
      - TRACKER_USE_NEW_DONATE_LAYOUT=False
    ports:
      - "8000:8000"
  web:
    image: "esamarathon/tracker-statics:latest"
    build:
      context: .
      dockerfile: Dockerfile-statics
    volumes:
#      - "static:/var/www/html/static/:ro"
      - "./nginx_dev.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8080:80"
    depends_on:
      - app
volumes:
  static:
