name: Build and release

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  publish_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/bsgmarathon/tracker:latest
          cache-from: type=gha
          cache-to: type=gha